### PR TITLE
[feature.FEM.EdgeAndCornerConnectivity] New Feature: Edge and Vertex connectivity, needed for a FEM solver

### PR DESCRIPTION
**Pull request by fhindenlang**
We introduce a new version 1.3.0 of HOPR, where the mesh file is extended to provide element edge connectivity and element corner or "Vertex" connectivity, which is  needed for (high order) Finite Element solvers.

Version 1.3.0
- fixed 2d GMSH testcase, was failing now because all `stop`  calls have been replaced by `abort` 
- read-in flag to activate FEM output via `GenerateFEMConnectivity=T/F` (default is F) 
- HDF5 meshfile variable names of lower versions are kept, and new ones are added for `GenerateFEMConnectivity=T`
  see documentation for the updated mesh format. The following changes to the meshfile are important:
  - additional information on the element level is stored in `FEMElemInfo` 
  - edge connectivity information ( arrays `EdgeInfo` and `EdgeConnectInfo` )
  - vertex connectivity information ( arrays `VertexInfo` and `VertexConnectInfo`)
- Visualization of FEM connectivity of the mesh in paraview:
      - `DebugMesh_Faces.vtu` visualizes all element faces with their element ID and uniqueFaceID.
      - `DebugMesh_Edges.vtu` visualizes all element edges (1D lines) with their element ID and uniqueEdgeID, and VertexIDs and their master/slave status
 - Note that the edge and vertex connectivity has been implemented only for conforming meshes. If a non-conforming mesh is found, the default  `GenerateFEMConnectivity=F` will be used.

TODOs before merge:
- [x] Add read-in flag  `GenerateFEMConnectivity=T/F`to activate FEM output with new container `FEMElemInfo` in order to not change the original container `ElemInfo`
- [x] implement vertex connectivity
- [x] check edge+vertex connectivity implementation in simulations @OttTs 
    - [x] non-periodic
    - [x] periodic
    - [x] unstructured
- [x] Descriptions for new/changed routines
    - [x] Short header description (do not just spell out the name of the subroutine, units for important variables if applicable) 
    - [x] Workflow
      - [x] Short summary in the header 
      - [x] Inside the routine at the appropriate positions
- [x] Regression tests
    - [x]  `GenerateFEMConnectivity=T/F` (default is F) @fhindenlang 
      - [x] non-periodic
      - [x] periodic
      - [x] unstructured
      - [x] curved $N=2,3$: Case(4) used
- [x] Check if all `STOP` additionally return `!= 0`, replace with `abort()` @scopplestone 
- [x] Remove line breaks from all `abort()` calls @scopplestone 
- [x] Check correct deallocation of new pointer structures by running memory checker for leaks @kopperp
- [x] Remove leading white spaces from all old and new .ini files @scopplestone 
- [x] Visualize FEM connectivity of the mesh in paraview:
      - `DebugMesh_Faces.vtu` visualizes all element faces with their element ID and uniqueFaceID.
      - `DebugMesh_Edges.vtu` visualizes all element edges (1D lines) with their element ID and uniqueEdgeID, and VertexIDs and their master/slave status

### CODE REVIEW

**Comment by fhindenlang** [comment]
Hi everbody, lets dicuss here the further developments.

**Comment by fhindenlang** [comment]
ok, so I think we have now a running version with edge and vertex connectivity. 

I changed the elemInfo back to its original, and added the Flag `FEMconnect="ON"/"OFF"` to the hdf5 file. (Mortar meshes will still have that flag being "OFF", since mortar edges are not yet implemented!)
 - We wanted current hdf5 readers to have no problem with the eleminfo being larger. 
- DG code users can decide if they even need the FEM edge and vertex connectivity information.
- only if `FEMconnect="ON"`, we write the `FEMElemInfo;EdgeInfo;EdgeConnectInfo;VertexInfo;VertexConnectInfo` arrays to the meshfile!
TODOS:
- [ ] We still need (with a FEM code) if the information now given in the HDF5 file is meaningful!!

**Comment by fhindenlang** [comment]
So I added some cases for the "sphere in cube" in `tutorials/4-02`, which are conforming curved meshes of a box in [-1,1], and there are mulitple 
cases for full/2D/1D/no periodicity. 
@OttTs These meshes can be used for testing against an exact solution with dirichlet BCs.

**Comment by fhindenlang** [comment]
opened an issue #56, since checks are failing, but not only because of the new feature. Actually, the `meshdim=2d` does not work in the gmsh test.

**Comment by fhindenlang** [comment]
I did not yet fix the FEMconnectivity cases, they seem to have a problem with periodicity...

**Comment by fhindenlang** [comment]
@OttTs Now that the unstructured meshes in `tutorials/4-02-unstruct_curved_FEMconnect`  are working, could you try to run them with your FEM solver?

**Comment by fhindenlang** [comment]
Very good tobi! I think we then can move forward!Btw: If you set one degree of freedom to zero, you could set it to the exact solution instead!Florian HindenlangBereiteranger 381541 MünchenHandy: +491635674337Am 05.02.2024 um 17:56 schrieb Tobias Ott ***@***.***>:﻿

@OttTs Now that the unstructured meshes in tutorials/4-02-unstruct_curved_FEMconnect are working, could you try to run them with your FEM solver?

The meshes all seem to work. For the fully periodic case, I'm having some trouble getting the convergence test to work due to the constant offset.

**Review by kopperp — APPROVED** [review]

**Comment by fhindenlang** [comment]
TITEL OF RELEASE:
Build and write FEM "Edge" and "Vertex" connectivity information  (flag: `GenerateFEMConnectivity=T/F`, default is `F`). Adds new variables to existing hdf5 meshfile.

**Pull request merged**
