### PR TITLE
Documentation: Tutorials

### PR DESCRIPTION
**Pull request by schuettem**
Copy Tutorials from old Docu into new Docu

### CODE REVIEW

**Comment by scopplestone** [comment]
The large image files should be reduced in size (and removed from the history) and re-committed.

**Comment by schuettem** [comment]
I reduced some of the large images. The largest image is now 367,2 kB. Is this still too large or ok? These changes are not committed yet, because I don't know how to remove a file from the git history.

**Comment by scopplestone** [comment]
367,2 kB should be O.K.

You can fix the history by, e.g., over-writing the last commit (which is okay if you are the only one working on the branch)

 ```
git add path/to/my/changed/file
git commit --amend --date=now
git push --force-with-lease origin improvement.documentation
 ```

This will destroy the previous commit hash and generate a new one.

**Comment by kopperp** [comment]
The uploaded version is a good first draft, but still needs some work with shortening, sanity checking and proof-reading. To distribute this work, please pick one of the following list:

Completed:
- [x] blockstructuredmeshes.md
- [x] index_inbuiltmeshgenerators.md

In progress:
- [x] straightedgedboxes.md

ToDo:
- [ ] curvedmeshes.md
- [ ] externalmesheswithcurvedboundaries.md
- [ ] externalmesheswithoutcurvedboundaries.md
- [ ] generationofhexahedralmeshes.md
- [ ] hoproutputparameter.md
- [ ] index_agglomeration.md
- [ ] index_externalmeshes.md
- [ ] index_postprocessing.md
- [ ] index_visualization.md
- [ ] meshrefinement.md
- [ ] meshuncurving.md
- [ ] visualizationwithparaview.md

**Comment by tietz-r** [comment]
I read the visualization with paraview file. There is a mention to a custom filter which you can import, but I cannot find this filter anywhere. Do you know, where it is otherwise I would delete the corresponding section...

**Comment by kopperp** [comment]
> I read the visualization with paraview file. There is a mention to a custom filter which you can import, but I cannot find this filter anywhere. Do you know, where it is otherwise I would delete the corresponding section...

I think that reference was actually to the FLEXI ParaView-Plugin which effectively wraps the `posti_visu`/`piclas2vtk` runtime and writes the output directly into ParaView's memory. A bit more detail is given in the [FLEXI documentation](https://numericsresearchgroup.org/userguide/userguide.pdf) but I fully agree that this section does not belong in the HOPR documentation.

**Pull request merged**
