### PR TITLE
[philippOff:master] The CGNS data types have been updated to build hopr with an up-to-date software stack

### PR DESCRIPTION
**Pull request by philippOff**
DATATYPE -> CG_DATATYPE

Tested with gcc-12.1.1, OpenMPI-4.1.2, CGNS-4.2.0 (int-32) and HDF5-1.12.0

### CODE REVIEW

**Comment by kopperp** [comment]
Are there any downsides to raising the included CGNS version in `CMakeListsLib.txt` to `4.2.0` as well? Other than that, LGTM.

**Review by kopperp — APPROVED** [review]
Are there any downsides to raising the included CGNS version in `CMakeListsLib`.txt to `4.2.0` as well? Other than that, LGTM.

**Comment by pnizenkov** [comment]
Does this only work on the HAWK? Or how is this supposed to work? I cannot compile this locally.

**Comment by kopperp** [comment]
Current idea is to hide these data types behind a preprocessor flag. Philipp, do you have a machine where we can reproduce this build?

**Comment by philippOff** [comment]
Yes, I have a machine where I can reproduce this build.

**Comment by kopperp** [comment]
Can you check the data types in the CGNS header file (`/usr/include/cgnslib.h` if you installed it system-wide)? If we can get the correct names from this file, we can just hide all the changes with preprocessor prefixes.

**Comment by scopplestone** [comment]
closed because out-of-date

**Pull request closed without merging**
