### PR TITLE
[update.cgns.version.v4.3.0] Updated default CGNS version to v4.3.0

### PR DESCRIPTION
**Pull request by scopplestone**
- [x] CGNS v4.3.0 from https://github.com/CGNS/CGNS.git is now default
- [x] Merge #21 before merging this branch as it contains the new github actions functionality

### CODE REVIEW

**Comment by scopplestone** [comment]
===> EXECUTING TUTORIAL:  2-01-external_mesh_sphere , WITH INIFILE: parameter.ini
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP 1
 Node=           16  x=    2.3715151000379834E-322   0.0000000000000000        9.3329000499411472E-321
 Node=           17  x=    2.3715151000379834E-322   0.0000000000000000        9.3329000499411472E-321
 Node=           18  x=    2.3715151000379834E-322   0.0000000000000000        9.3329000499411472E-321

 _____________________________________________________________________________
 Program abort caused in File : src/mesh/mesh_basis.f90 Line          450
 This file was compiled at Dec 14 2022  17:48:56
 Message: Unknown 3D Elem%nNodes in CreateSides
See SPHERE_ERRORS.out for more details


===> EXECUTING TUTORIAL:  2-02-external_mesh_sphere_curved , WITH INIFILE: parameter.ini
STOP 1
 Read Zone Zone_1_1
    read section ZONE_1
    read section BC_sphere

 _____________________________________________________________________________
 Program abort caused in File : src/readin/readin_CGNS.f90 Line          385
 This file was compiled at Dec 14 2022  17:53:13
 Message: Something wrong with surf element numbers in CGNS File zone :       1
See SPHERE_CURVED_ERRORS.out for more details

**Comment by pnizenkov** [comment]
The CGNS read-in seems to work again with the last commit. However, there are a few other error when compiling with Debug.

**Comment by pnizenkov** [comment]
Unrelated to CGNS, but there are a few other errors when compiling with Debug:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GLOBAL UNIQUE NODES ...
   All Nodes sorted...
   Number of nodes to check:           60
    size of tolerance box:                    1

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x14e9e011251f in ???
        at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x510d94 in __mod_globaluniquenodes_MOD_globaluniquenodes
        at /home/nizenkov/Workspace/hopr_github/src/mesh/globaluniquenodes.f90:301
#2  0x4418bb in __mod_mesh_connect_MOD_connect
        at /home/nizenkov/Workspace/hopr_github/src/mesh/mesh_connect.f90:177
#3  0x429fc2 in __mod_mesh_MOD_fillmesh
        at /home/nizenkov/Workspace/hopr_github/src/mesh/mesh.f90:569
#4  0x406425 in hopr
        at /home/nizenkov/Workspace/hopr_github/src/hopr.f90:85
#5  0x4067c7 in main
        at /home/nizenkov/Workspace/hopr_github/src/hopr.f90:29

18/24 Test #15: buildTest:1-08-curved-sphere:parameter_shell.ini ..............   Passed    0.84 sec
19/24 Test #22: buildTest:2-04-external_Specmesh_curved:parameter_KT3.ini .....   Passed    0.91 sec
20/24 Test #12: buildTest:1-06-curved-postdeform:parameter3.ini ...............   Passed    1.26 sec
21/24 Test #23: buildTest:3-01-agglomeration_NACA:parameter.ini ...............   Passed    1.75 sec
22/24 Test #17: buildTest:1-11-postdeform_nonconforming:parameter.ini .........   Passed    1.83 sec
23/24 Test #21: buildTest:2-03-external_mesh_Gmsh_curved:parameter.ini ........   Passed    2.26 sec
24/24 Test #24: buildTest:3-02-agglomeration_sphere:parameter.ini .............   Passed    3.55 sec

83% tests passed, 4 tests failed out of 24

Total Test time (real) =   3.55 sec

The following tests FAILED:
          4 - buildTest:1-01-cartbox:parameter_ex1.ini (NUMERICAL)
          5 - buildTest:1-01-cartbox:parameter_ex2.ini (NUMERICAL)
          6 - buildTest:1-02-cartbox_periodic:parameter.ini (NUMERICAL)
         16 - buildTest:1-09-cartbox_nonconforming:parameter.ini (NUMERICAL)
```

**Comment by scopplestone** [comment]
> Unrelated to CGNS, but there are a few other errors when compiling with Debug:
> 
> ```
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> GLOBAL UNIQUE NODES ...
>    All Nodes sorted...
>    Number of nodes to check:           60
>     size of tolerance box:                    1
> 
> Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
> 
> Backtrace for this error:
> #0  0x14e9e011251f in ???
>         at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
> #1  0x510d94 in __mod_globaluniquenodes_MOD_globaluniquenodes
>         at /home/nizenkov/Workspace/hopr_github/src/mesh/globaluniquenodes.f90:301
> #2  0x4418bb in __mod_mesh_connect_MOD_connect
>         at /home/nizenkov/Workspace/hopr_github/src/mesh/mesh_connect.f90:177
> #3  0x429fc2 in __mod_mesh_MOD_fillmesh
>         at /home/nizenkov/Workspace/hopr_github/src/mesh/mesh.f90:569
> #4  0x406425 in hopr
>         at /home/nizenkov/Workspace/hopr_github/src/hopr.f90:85
> #5  0x4067c7 in main
>         at /home/nizenkov/Workspace/hopr_github/src/hopr.f90:29
> 
> 18/24 Test #15: buildTest:1-08-curved-sphere:parameter_shell.ini ..............   Passed    0.84 sec
> 19/24 Test #22: buildTest:2-04-external_Specmesh_curved:parameter_KT3.ini .....   Passed    0.91 sec
> 20/24 Test #12: buildTest:1-06-curved-postdeform:parameter3.ini ...............   Passed    1.26 sec
> 21/24 Test #23: buildTest:3-01-agglomeration_NACA:parameter.ini ...............   Passed    1.75 sec
> 22/24 Test #17: buildTest:1-11-postdeform_nonconforming:parameter.ini .........   Passed    1.83 sec
> 23/24 Test #21: buildTest:2-03-external_mesh_Gmsh_curved:parameter.ini ........   Passed    2.26 sec
> 24/24 Test #24: buildTest:3-02-agglomeration_sphere:parameter.ini .............   Passed    3.55 sec
> 
> 83% tests passed, 4 tests failed out of 24
> 
> Total Test time (real) =   3.55 sec
> 
> The following tests FAILED:
>           4 - buildTest:1-01-cartbox:parameter_ex1.ini (NUMERICAL)
>           5 - buildTest:1-01-cartbox:parameter_ex2.ini (NUMERICAL)
>           6 - buildTest:1-02-cartbox_periodic:parameter.ini (NUMERICAL)
>          16 - buildTest:1-09-cartbox_nonconforming:parameter.ini (NUMERICAL)
> ```

this has now been fixed in 2c5e0a81801958f3058dc5d6d0342e84d565a84f

**Comment by scopplestone** [comment]
> The CGNS read-in seems to work again with the last commit. However, the new function `CG_POLY_ELEMENTS_READ_F` is only available with version 4.3.0, thus we still need a preprocessor flag or something like that to be able to compile with 3.4.1.

a pre-processor variable `-DPP_CGNS_VERSION=v430` has now been introduced in 2c5e0a81801958f3058dc5d6d0342e84d565a84f, which can be set to the currently used CGNS version. However, still missing is setting this variable corretcly when
  a) CGNS is compiled multiple times with `LIBS_BUILD_CGNS=ON` but for different versions (re-name the folder might fix this)
  b) CGNS is pre-compiled, can the version be extracted or found in a safe way?

**Pull request merged**
